config/routes.rb
SampleApp::Application.routes.draw do
  get "microposts/create"
  get "microposts/destroy"
  get "tests/new"
  resources :users
  resources :sessions , :only => [:new, :create, :destroy]
  resources :microposts, :only => [:destroy, :create]
  
  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  
  root 'pages#home'
  get '/pages/help', :to => 'pages#help', :as => 'help'
  get '/pages/home', :to => 'pages#home'
  get '/pages/about', :to => 'pages#about', :as => 'about'
  get '/pages/contact', :to => 'pages#contact', :as => 'contact'
  get '/signup', :to => 'users#new', :as => 'signup'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  
  belongs_to :user
  
  default_scope :order => "microposts.created_at DESC"
  
  validates :user_id, :presence => true
  validates :content, :presence => true,
                      :length => { :maximum => 140 }
  
end

app/models/test.rb
class Test < ActiveRecord::Base
	attr_accessible :name, :subject
	
	validate :name, :length => {:within => 1..20},
					:presence => true
	
	validate :subject, :length => {:within => 1..20},
				 	   :presence => true
					 
	before_save :mark_gen
	
	private
	
	def mark_gen
		self.mark = "#{name} #{subject}"
	end
	
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  username   :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

require 'digest'

class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :username, :email, :password, :password_confirmation
  
  has_many :microposts, :dependent => :destroy
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :username, :presence => true,
						 :length => {:maximum => 50}
	validates :email, :presence => true,
					  :format => { :with => email_regex },
					  :uniqueness => true
  	validates :password, :presence => true,
	  					 :length => {:within => 5..20},
						 :confirmation => true
						 
 	before_save :encrypt_password
	 
	def has_password?(submitted_password)
		self.encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password)
		user = User.find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
	 
	private
	
	def encrypt_password
		self.salt = make_salt if new_record?
		self.encrypted_password = encrypt(password)
	end
	
	def encrypt(string)
		secure_hash("#{salt}--#{string}")
	end
	
	def make_salt
		secure_hash("#{Time.now.utc}--#{password}")
	end
	
	def secure_hash(string)
		Digest::SHA2.hexdigest(string)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  
  before_filter :authenticate, :only => [:create, :destroy]
  
  def create
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
    @title = "about"
  end

  def contact
    @title = "contact"
  end
  
  def help
    @title = "help"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create  
    user = User.authenticate(params[:session][:email], params[:session][:password]) 
    if user.nil?
      flash.now[:error] = "Invalid Username/Password combination"
      render 'new'
    else
      sign_in user
      redirect_to_prev user
    end
  end
  
  def destroy
     signed_out
     redirect_to root_path
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  attr_acccessor :name, :subject
  
  def initialize(attributes = {})
    @name = attributes[:name]
    @subject = attributes[:subject]
  end
  
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate, :only => [:edit, :update, :index]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :is_admin, :only => :destroy
  
  def new
    @user = User.new
    @title = 'Sign up'
  end
  
  def create
    @user = User.new(params[:user])
    if(@user.save)
      sign_in @user
      flash[:success] = "Welcome to the sample app!"
      redirect_to @user
    else
      render 'new'
      @title = "Sign up"
    end
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.username
  end
  
  def edit
    #@user = User.find(params[:id])
    @title = "Edit Profile"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit User"
      render 'edit'
    end
  end
  
  def index
    @users = User.paginate(:page=>params[:page])
    @title = "User information"
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end
  
  private
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
  
  def is_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def title
		base_title = "Ruby on Rails tutorial"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
  
  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def signed_out
    cookies.delete(:remember_token)
    current_user = nil
  end
  
  def deny_access
    save_prev_location
    redirect_to signin_path, :notice => "You need to sign in before changing profile!"
  end
  
  def redirect_to_prev(default)
    next_location = session[:return_to] || default  
    redirect_to next_location
  end
  
  def current_user?(user)
    user == current_user
  end
  
  private
  
  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end
  
  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
  
  def save_prev_location
    session[:return_to] = request.fullpath
  end
    
  def clean_saved_location
    session[:return_to] = nil
  end
  
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {:size=>50})
		gravatar_image_tag(user.email.downcase, :alt => user.username,
			:class => 'gravatar',
			:gravatar => options)
	end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", "http://news.railstutorial.org/" %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<% logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %>
	<%= link_to logo, root_path%>
	<nav class = "round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
       <li><%= link_to "Settings", edit_user_path(current_user) %></li>
       <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
       <li><%= link_to "Users", users_path%></li>
     <% else %>
       <li><%= link_to "Sign in", signin_path %></li>
       <% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'print', :media => 'print' %>
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<html>
	<head>
		<title> <%= title %> </title>
    <%= csrf_meta_tag %>
		<%= render "layouts/stylesheets" %>
    <%= javascript_include_tag "application" %>
	</head>
  
	<body>
		<div class = "container">
			<%= render "layouts/header" %>
			<section class="round">
        <% flash.each do |key, value| %>
        <div class = "flash <%= key %>"><%= value %></div>
        <% end %>
				<p> The page contains: <%= yield %> </p>
			</section>
			<%= render "layouts/footer" %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>
	

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class='content'><%= micropost.content %></span>
    <span class='timestamp'>
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
</tr> 

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>

app/views/pages/about.html.erb
<html>

<body>
	<p><%= title %></p>
	<p> About tutorial information! </p>
</body>

</html>
	

app/views/pages/contact.html.erb
<html>

<body>
	<p><%= title %></p>
	<p> Contact information! </p>
</body>

</html>

app/views/pages/help.html.erb
<html>
	<head>
		<title> Ruby on Rails tutorial | <%= @title %> </title>
	</head>
	
	<body>
		<p> Help information! </p>
	</body>
	
</html>

app/views/pages/home.html.erb
<html>

<body>
	<p><%= title %></p>
	<p>Home page information! </p>
</body>

<%= link_to "Sign up", signup_path, :class => "signup_button round" %>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from begin saved: </h2>
    <p> There were problems with the followng fields: </p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end%>
    </ul>
  </div>
<%end%>
    

app/views/users/_user.html.erb
  <li>
    <%= gravatar_for user, :size => 30 %>
    <%= link_to user.username, user %>
    <% if current_user.admin? %>
    <%= link_to "delete", user, :method => :delete,
        :confirm => "Are you sure?", :title => "Delete?" %>
    <% end %>
  </li>

app/views/users/edit.html.erb
<html>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  
  <div class = 'field'>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </div>
  
  <div class = 'field'>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  
  <div class = 'field'>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  
  <div class = 'field'>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div class = "actions">
    <%= f.submit "Update" %>
  </div>
  <% end %>
  
  <div>
  <%= gravatar_for @user %>
  <a href = "http://gravatar.com/emails">change</a>
  </div>

</html>

app/views/users/index.html.erb
<html>
<%= will_paginate %>
<h1> Registered Users </h1>

<ul class = "@users">
  <%= render @users %>
</ul>
<%= will_paginate @users%>

</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages", :object => f.object %>
  <div class = "field">
		<%= f.label :username %><br/>
		<%= f.text_field :username %>
	</div>
  <div class = "field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class = "field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class = "field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class = "actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
      <% unless @user.microposts.empty? %>
        <%= render @microposts %>
        <%= will_paginate @microposts %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.username %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
    </td>
  </tr>
</table>